basePath: /api/v1
definitions:
  model.Form:
    properties:
      creationDate:
        type: string
      hierarchy:
        type: string
      id:
        type: string
      modifiedDate:
        type: string
      sections:
        items: {}
        type: array
      typeForm:
        type: string
    type: object
  model.Hierarchy:
    properties:
      id:
        type: string
      lat:
        type: string
      lng:
        type: string
      name:
        type: string
      provincias:
        items: {}
        type: array
    type: object
  model.Inventory:
    properties:
      creationDate:
        type: string
      details: {}
      hierarchy:
        type: string
      hierarchyId:
        type: string
      id:
        type: string
      index:
        type: string
      institucionId:
        type: string
      modifiedDate:
        type: string
      typeInvetory:
        type: string
    type: object
  util.Error:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Backend enfocado de formulario de jarquías para Pnrrd
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Documentación Servicio formularios Pnrrd
  version: "1.0"
paths:
  /forms:
    get:
      operationId: get-form
      parameters:
      - description: Tipo de formulario, que puede ser INFORMATION o RESOURCE
        in: query
        name: type
        required: true
        type: string
      - description: Jerarquía del  formulario, por defecto solo se maneja general
        in: query
        name: hierarchy
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Form'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.Error'
      summary: Obtener formulario general o de recursos para una jerarquía especifica
      tags:
      - forms
    post:
      consumes:
      - application/json
      operationId: create-form
      parameters:
      - description: Crear Formulario
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/model.Form'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Form'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.Error'
      summary: crear un nuevo formulario
      tags:
      - forms
  /hierarchies:
    get:
      operationId: get-hierarchy
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Hierarchy'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.Error'
      summary: Obtener la lista de jerarquias, agrupadas en Regiones-Provincias-Comunas
      tags:
      - hierarchy
  /inventories:
    get:
      description: |-
        Con este servicio se puede obtener el inventario.
        Existen 2 tipos de inventario, de información ( tag INFORMATION ) y recursos ( tag RESOURCE). El primero enfocado en las capacidades y el segundo en  información institucional.
        Siempre que se quiera obtener la información institucional en parámetro hierarchy debe ir “NACIONAL”.
      operationId: get-inventory
      parameters:
      - description: Id de institución
        in: query
        name: institution
        required: true
        type: string
      - description: Tipo de jararquía de inventario solicitado
        in: query
        name: hierarchy
        required: true
        type: string
      - description: Id de la jerarquía solicitada, solo requerido si no es jerarquia
          nacional
        in: query
        name: hierarchy_id
        type: string
      - description: tipo de inventario solicitado (puede ser INFORMATION o RESOURCE)
        in: query
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Inventory'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.Error'
      summary: Obtener inventario de una institución, para una jerarquía especifica
      tags:
      - inventory
    put:
      consumes:
      - application/json
      operationId: update-inventory
      parameters:
      - description: Actualizar inventario
        in: body
        name: inventory
        required: true
        schema:
          items:
            $ref: '#/definitions/model.Inventory'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Inventory'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.Error'
      summary: Ingresar actualizaciones de inventario, para una institución
      tags:
      - inventory
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
